# Generated by Django 3.0 on 2021-04-15 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carrera',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_carrera', models.CharField(choices=[('1', 'Moto'), ('2', 'Karting')], max_length=1)),
                ('nombre', models.CharField(max_length=50)),
                ('fecha', models.DateField()),
                ('lugar', models.CharField(max_length=80)),
                ('precio', models.BigIntegerField()),
            ],
        ),
    ]
